const pdfParse = require('pdf-parse');
const mammoth = require('mammoth');

/**
 * Convert HTML generated by Mammoth into structured plain text,
 * preserving list numbering (1., 2. for outer lists; A., B., C. for inner lists),
 * table cells, and line breaks.
 */
function convertMammothHtmlToText(html) {
  if (!html || typeof html !== 'string') return '';

  let text = html;

  // Mark bolded or highlighted text as potential correct option marker if it matches option structure
  text = text.replace(/<(?:strong|b|mark)>(\s*[\(\[]?[A-Da-d1-5][\.\)\]\:\-].*?)<\/(?:strong|b|mark)>/gi, '*$1');

  // Format tables: separate cells with newlines so table options render on individual lines
  text = text.replace(/<\/td>/gi, '\n');
  text = text.replace(/<\/tr>/gi, '\n');
  text = text.replace(/<tr[^>]*>/gi, '');
  text = text.replace(/<td[^>]*>/gi, '');

  // Format line breaks and headers
  text = text.replace(/<br\s*\/?>/gi, '\n');
  text = text.replace(/<\/h[1-6]>/gi, '\n\n');
  text = text.replace(/<\/p>/gi, '\n');

  // Process <ol> and <ul> list structures inspecting attributes (e.g. type="a", type="A", type="1")
  let listContextStack = [];

  text = text.replace(/<(\/)?(ol|ul|li)([^>]*)>/gi, (match, isClose, tag, attrs) => {
    tag = tag.toLowerCase();

    if (tag === 'ol' || tag === 'ul') {
      if (isClose) {
        listContextStack.pop();
        return '\n';
      } else {
        let listType = '1';
        if (tag === 'ol') {
          const typeMatch = attrs ? attrs.match(/type=["']?([aAiI1])["']?/i) : null;
          if (typeMatch) {
            listType = typeMatch[1];
          } else if (listContextStack.length > 0) {
            listType = 'a'; // Nested lists default to alpha
          }
        } else {
          listType = 'bullet';
        }
        listContextStack.push({ type: listType, count: 0 });
        return '\n';
      }
    } else if (tag === 'li') {
      if (isClose) {
        return '\n';
      } else {
        if (listContextStack.length > 0) {
          const currentCtx = listContextStack[listContextStack.length - 1];
          currentCtx.count++;
          const count = currentCtx.count;
          const type = currentCtx.type;

          if (type === 'a' || type === 'A') {
            const letter = String.fromCharCode((type === 'A' ? 64 : 96) + count);
            return `\n${letter}) `;
          } else if (type === 'i' || type === 'I') {
            return `\n(${count}) `;
          } else if (type === 'bullet') {
            return `\n• `;
          } else {
            // Standard ordered list '1'
            // If in a nested list context, render as A), B), C)...
            if (listContextStack.length > 1) {
              const letter = String.fromCharCode(64 + count);
              return `\n${letter}) `;
            }
            return `\n${count}. `;
          }
        }
        return '\n• ';
      }
    }
    return '';
  });

  // Strip remaining HTML tags
  text = text.replace(/<[^>]+>/g, '');

  // Remove duplicate prefixes generated when user typed manual numbers inside list items (e.g., "1. 1. What is")
  text = text
    .replace(/^(\d{1,3}[\.\)])\s*\1\s*/gm, '$1 ')
    .replace(/^([A-Da-d][\.\)])\s*\1\s*/gm, '$1 ');

  // Decode HTML entities
  text = text
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");

  return text;
}

/**
 * Extracts raw text from uploaded PDF or DOCX file buffer
 */
async function extractTextFromBuffer(buffer, mimetype) {
  if (mimetype.includes('pdf')) {
    const data = await pdfParse(buffer);
    return data.text;
  } else if (mimetype.includes('wordprocessingml') || mimetype.includes('docx') || mimetype.includes('doc')) {
    try {
      // Use convertToHtml so Word auto-numbered lists (<ol><li>) retain list structure & numbers
      const htmlResult = await mammoth.convertToHtml({ buffer });
      if (htmlResult && htmlResult.value && htmlResult.value.trim().length > 0) {
        const convertedText = convertMammothHtmlToText(htmlResult.value);
        if (convertedText && convertedText.trim().length > 20) {
          return convertedText;
        }
      }
    } catch (err) {
      console.warn('Mammoth HTML conversion fallback to raw text:', err.message);
    }
    // Fallback to raw text extraction
    const rawResult = await mammoth.extractRawText({ buffer });
    return rawResult.value;
  } else {
    // Fallback to plain text
    return buffer.toString('utf-8');
  }
}

/**
 * Preprocesses raw text: normalizes line endings and splits single-line options
 * E.g., "A) Apple   B) Banana   C) Cherry   D) Date" -> 4 separate lines
 */
function preprocessText(rawText) {
  if (!rawText || typeof rawText !== 'string') return '';

  const cleanText = rawText.replace(/\r\n/g, '\n').replace(/\r/g, '\n').replace(/\u00a0/g, ' ');
  const lines = cleanText.split('\n').map(l => l.trim()).filter(Boolean);
  const resultLines = [];

  // Regex to detect multiple options on a single line
  // e.g. "A) Opt 1   B) Opt 2   C) Opt 3" or "A. Opt 1   B. Opt 2" or "(A) Opt 1 (B) Opt 2"
  const multiOptionPattern = /(?:^|\s+)(?:[\(\[]?([A-Da-d1-4])[\.\)\]]\s*|\b([A-Da-d])[\.\)]\s+)/g;

  for (const line of lines) {
    const matches = [...line.matchAll(multiOptionPattern)];
    
    // If line has 2 or more option markers (e.g. contains A and B, or B and C)
    if (matches.length >= 2) {
      let lastIdx = 0;
      for (let i = 0; i < matches.length; i++) {
        const match = matches[i];
        const matchStart = match.index;

        if (i === 0 && matchStart > 0) {
          const prefix = line.substring(0, matchStart).trim();
          if (prefix) resultLines.push(prefix);
        }

        const nextStart = (i < matches.length - 1) ? matches[i + 1].index : line.length;
        const optionChunk = line.substring(matchStart, nextStart).trim();
        if (optionChunk) resultLines.push(optionChunk);
      }
    } else {
      resultLines.push(line);
    }
  }

  return resultLines.join('\n');
}

/**
 * Smart Regex Parser to convert plain text question paper into structured questions & options
 */
function parseQuestionsFromText(rawText) {
  if (!rawText || typeof rawText !== 'string') return [];

  const processedText = preprocessText(rawText);
  const lines = processedText.split('\n').map(l => l.trim()).filter(Boolean);

  const rawQuestions = [];
  let currentQuestion = null;

  // Question Header Regex Patterns:
  // Matches: "Q1.", "Q1:", "Q1 -", "Question 1.", "Question 1:", "Que 1.", "1.", "1)", "1:", "1 -", "(1)", "[1]", "I.", "II."
  const questionHeaderRegex = /^(?:Q(?:uestion|ue)?\.?\s*(\d+)|(?:Q|\b)(\d{1,3})[\.\)\:\-\/]|\[(\d{1,3})\]|\((\d{1,3})\)|(?:[I|V|X]{1,4})[\.\)\:\-])\s*[:\-]?\s*(.*)/i;

  // Option Regex Patterns:
  // Matches: "A)", "A.", "(A)", "[A]", "a)", "a.", "*A)", "* A.", "A -", "A :"
  const optionRegex = /^(?:\*\s*)?(?:[\(\[]?([A-Da-d1-5])[\.\)\]\:\-]\s*|\b([A-Da-d])[\.\)]\s+)(.*)/;

  // Answer Key Regex Patterns:
  // Matches: "Answer: B", "Ans: (C)", "Correct Answer: Option A", "Ans - D"
  const answerHeaderRegex = /^(?:Answer|Ans|Correct Answer|Correct)\s*[:\-]?\s*(?:Option\s*)?\(?([A-Da-d1-5])\)?/i;

  // Global Answer Key section regex at end of text (e.g. "Answer Key:", "Answers: 1-A, 2-B, 3-C")
  const globalAnswerKeyHeaderRegex = /^(?:Answer Key|Answers|Correct Answers)\s*[:\-]?/i;
  let globalAnswersMap = {};
  let inAnswerKeySection = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Check for global answer key section header or lines
    if (globalAnswerKeyHeaderRegex.test(line)) {
      inAnswerKeySection = true;
    }

    if (inAnswerKeySection) {
      const keyPairs = [...line.matchAll(/(\d+)\s*[\.\:\-\=]\s*\(?([A-Da-d1-5])\)?/g)];
      if (keyPairs.length > 0) {
        for (const kp of keyPairs) {
          globalAnswersMap[kp[1]] = kp[2].toUpperCase();
        }
        continue;
      } else if (line.match(globalAnswerKeyHeaderRegex)) {
        continue;
      }
    }

    // Check if line indicates correct answer for current question (e.g. "Answer: B")
    const ansMatch = line.match(answerHeaderRegex);
    if (ansMatch && currentQuestion) {
      currentQuestion.correct_answer = ansMatch[1].trim().toUpperCase();
      continue;
    }

    // Check if line starts a new question header
    const qMatch = line.match(questionHeaderRegex);
    if (qMatch) {
      const qNum = qMatch[1] || qMatch[2] || qMatch[3] || qMatch[4] || '';
      const qText = qMatch[5] || line;

      if (currentQuestion && currentQuestion.options.length >= 2) {
        rawQuestions.push(currentQuestion);
      }
      currentQuestion = {
        num: qNum,
        question_text: qText.trim(),
        options: [],
        correct_answer: '',
        marks: 1
      };
      continue;
    }

    // Check if line is an option (e.g. "A) React", "B. Vue", "(C) Angular", "*D) Svelte")
    const optMatch = line.match(optionRegex);
    if (optMatch) {
      const optKey = (optMatch[1] || optMatch[2] || '').toUpperCase();
      const optText = optMatch[3] || line;
      const isAsteriskCorrect = line.startsWith('*');

      // SAFEGUARD 1: If currentQuestion already has an option with this key (e.g. A),
      // or has >= 4 options and we see key A again, it signals a NEW QUESTION block!
      if (currentQuestion && currentQuestion.options.some(o => o.key === optKey)) {
        if (currentQuestion.options.length >= 2) {
          rawQuestions.push(currentQuestion);
        }
        currentQuestion = {
          question_text: 'Question',
          options: [],
          correct_answer: '',
          marks: 1
        };
      }

      // SAFEGUARD 2: If no currentQuestion exists, create one
      if (!currentQuestion) {
        currentQuestion = {
          question_text: 'Question',
          options: [],
          correct_answer: '',
          marks: 1
        };
      }

      const newOpt = {
        id: `opt_${currentQuestion.options.length + 1}`,
        text: optText.trim(),
        key: optKey
      };
      currentQuestion.options.push(newOpt);

      if (isAsteriskCorrect) {
        currentQuestion.correct_answer = optKey;
      }
      continue;
    }

    // Line is non-matching (neither question header, nor option, nor answer header)
    if (currentQuestion) {
      if (currentQuestion.options.length === 0) {
        // Still reading question text (multiline question text or code block)
        currentQuestion.question_text += '\n' + line;
      } else {
        // If currentQuestion ALREADY has 4 options (A, B, C, D) and line is a new sentence,
        // it is likely the question text for Question N+1 without an explicit number prefix!
        if (currentQuestion.options.length >= 4 && isLikelyQuestionSentence(line)) {
          rawQuestions.push(currentQuestion);
          currentQuestion = {
            question_text: line,
            options: [],
            correct_answer: '',
            marks: 1
          };
        } else {
          // Append to last option text
          const lastOpt = currentQuestion.options[currentQuestion.options.length - 1];
          lastOpt.text += '\n' + line;
        }
      }
    } else {
      // Create first question if text starts without explicit Q1 prefix
      if (line.length > 5 && !line.toLowerCase().startsWith('quiz') && !line.toLowerCase().startsWith('test')) {
        currentQuestion = {
          question_text: line,
          options: [],
          correct_answer: '',
          marks: 1
        };
      }
    }
  }

  // Push final question
  if (currentQuestion && currentQuestion.options.length >= 2) {
    rawQuestions.push(currentQuestion);
  }

  // Apply global answer map if present
  if (Object.keys(globalAnswersMap).length > 0) {
    rawQuestions.forEach((q, index) => {
      const qIndexStr = String(index + 1);
      const qNumStr = q.num || qIndexStr;
      const targetAns = globalAnswersMap[qNumStr] || globalAnswersMap[qIndexStr];

      if (targetAns && !q.correct_answer) {
        q.correct_answer = targetAns;
      }
    });
  }

  // Finalize all raw questions
  const questions = rawQuestions.map(q => finalizeQuestion(q));

  // Fallback: If no structured questions were found via regex, chunk text into 5-line blocks
  if (questions.length === 0 && lines.length >= 5) {
    let tempQ = null;
    lines.forEach((l, idx) => {
      if (idx % 5 === 0) {
        if (tempQ) questions.push(finalizeQuestion(tempQ));
        tempQ = { question_text: l, options: [], correct_answer: '', marks: 1 };
      } else if (tempQ && tempQ.options.length < 4) {
        tempQ.options.push({
          id: `opt_${tempQ.options.length + 1}`,
          text: l,
          key: String.fromCharCode(65 + tempQ.options.length)
        });
      }
    });
    if (tempQ && tempQ.options.length >= 2) {
      questions.push(finalizeQuestion(tempQ));
    }
  }

  return questions;
}

/**
 * Helper to determine if a line looks like a question header sentence
 */
function isLikelyQuestionSentence(line) {
  if (!line || line.length < 5) return false;
  if (line.endsWith('?')) return true;

  const lower = line.toLowerCase();
  const questionWords = ['what', 'which', 'how', 'why', 'who', 'where', 'when', 'explain', 'calculate', 'find', 'select', 'consider', 'identify'];
  return questionWords.some(w => lower.startsWith(w));
}

/**
 * Finalizes question structure, resolves correct_answer ID, cleans option objects
 */
function finalizeQuestion(q) {
  let correctId = q.options[0]?.id || 'opt_1';

  if (q.correct_answer) {
    const targetKey = q.correct_answer.toUpperCase();
    const matchedOpt = q.options.find(
      opt => opt.key === targetKey || opt.text.toLowerCase() === targetKey.toLowerCase()
    );
    if (matchedOpt) {
      correctId = matchedOpt.id;
    }
  }

  // Clean options array for output
  const cleanOptions = q.options.map((opt, i) => ({
    id: `opt_${i + 1}`,
    text: opt.text
  }));

  return {
    question_text: q.question_text,
    question_type: 'mcq',
    options: cleanOptions,
    correct_answer: correctId,
    marks: Number(q.marks) || 1,
    explanation: ''
  };
}

module.exports = {
  extractTextFromBuffer,
  preprocessText,
  parseQuestionsFromText
};


