import * as mammoth from 'mammoth';
import * as pdfjsLib from 'pdfjs-dist';

// Set up PDF.js worker
if (typeof window !== 'undefined' && pdfjsLib.GlobalWorkerOptions) {
  pdfjsLib.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version || '3.11.174'}/pdf.worker.min.js`;
}

/**
 * Convert HTML generated by Mammoth into structured plain text,
 * preserving list numbering (1., 2. for outer lists; A., B., C. for inner lists),
 * table cells, and line breaks.
 */
export function convertMammothHtmlToText(html) {
  if (!html || typeof html !== 'string') return '';

  let text = html;

  // Mark bolded or highlighted text as potential correct option marker if it matches option structure
  text = text.replace(/<(?:strong|b|mark)>(\s*[\(\[]?[A-Da-d1-5][\.\)\]\:\-].*?)<\/(?:strong|b|mark)>/gi, '*$1');

  // Format tables: separate cells with newlines so table options render on individual lines
  text = text.replace(/<\/td>/gi, '\n');
  text = text.replace(/<\/tr>/gi, '\n');
  text = text.replace(/<tr[^>]*>/gi, '');
  text = text.replace(/<td[^>]*>/gi, '');

  // Format line breaks and headers
  text = text.replace(/<br\s*\/?>/gi, '\n');
  text = text.replace(/<\/h[1-6]>/gi, '\n\n');
  text = text.replace(/<\/p>/gi, '\n');

  // Process <ol> and <ul> list structures inspecting attributes (e.g. type="a", type="A", type="1")
  let listContextStack = [];

  text = text.replace(/<(\/)?(ol|ul|li)([^>]*)>/gi, (match, isClose, tag, attrs) => {
    tag = tag.toLowerCase();

    if (tag === 'ol' || tag === 'ul') {
      if (isClose) {
        listContextStack.pop();
        return '\n';
      } else {
        let listType = '1';
        if (tag === 'ol') {
          const typeMatch = attrs ? attrs.match(/type=["']?([aAiI1])["']?/i) : null;
          if (typeMatch) {
            listType = typeMatch[1];
          } else if (listContextStack.length > 0) {
            listType = 'a'; // Nested lists default to alpha
          }
        } else {
          listType = 'bullet';
        }
        listContextStack.push({ type: listType, count: 0 });
        return '\n';
      }
    } else if (tag === 'li') {
      if (isClose) {
        return '\n';
      } else {
        if (listContextStack.length > 0) {
          const currentCtx = listContextStack[listContextStack.length - 1];
          currentCtx.count++;
          const count = currentCtx.count;
          const type = currentCtx.type;

          if (type === 'a' || type === 'A') {
            const letter = String.fromCharCode((type === 'A' ? 64 : 96) + count);
            return `\n${letter}) `;
          } else if (type === 'i' || type === 'I') {
            return `\n(${count}) `;
          } else if (type === 'bullet') {
            return `\n• `;
          } else {
            // Standard ordered list '1'
            if (listContextStack.length > 1) {
              const letter = String.fromCharCode(64 + count);
              return `\n${letter}) `;
            }
            return `\n${count}. `;
          }
        }
        return '\n• ';
      }
    }
    return '';
  });

  // Strip remaining HTML tags
  text = text.replace(/<[^>]+>/g, '');

  // Remove duplicate prefixes generated when user typed manual numbers inside list items
  text = text
    .replace(/^(\d{1,3}[\.\)])\s*\1\s*/gm, '$1 ')
    .replace(/^([A-Da-d][\.\)])\s*\1\s*/gm, '$1 ');

  // Decode HTML entities
  text = text
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");

  return text;
}

/**
 * Robustly extract text from PDF items by grouping text fragments on the same Y-coordinate line
 */
async function extractPdfText(arrayBuffer) {
  const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer });
  const pdf = await loadingTask.promise;
  let fullText = '';

  for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
    const page = await pdf.getPage(pageNum);
    const textContent = await page.getTextContent();

    if (!textContent || !textContent.items || textContent.items.length === 0) continue;

    // Sort items vertically (top to bottom), then horizontally (left to right)
    const items = [...textContent.items].sort((a, b) => {
      const yA = a.transform ? a.transform[5] : 0;
      const yB = b.transform ? b.transform[5] : 0;
      if (Math.abs(yA - yB) > 4) {
        return yB - yA; // Higher Y coordinate comes first on page
      }
      const xA = a.transform ? a.transform[4] : 0;
      const xB = b.transform ? b.transform[4] : 0;
      return xA - xB;
    });

    let lastY = null;
    let pageText = '';

    for (const item of items) {
      const str = item.str;
      if (str === undefined || str === null) continue;

      const currentY = item.transform ? item.transform[5] : null;

      if (lastY === null) {
        pageText += str;
      } else if (currentY !== null && Math.abs(currentY - lastY) > 4) {
        // New line on page
        pageText += '\n' + str;
      } else {
        // Same horizontal line: add space if needed
        if (pageText.length > 0 && !pageText.endsWith(' ') && !pageText.endsWith('\n') && !str.startsWith(' ')) {
          pageText += ' ';
        }
        pageText += str;
      }

      if (item.hasEOL) {
        pageText += '\n';
      }

      if (currentY !== null) {
        lastY = currentY;
      }
    }

    fullText += pageText + '\n\n';
  }

  return fullText;
}

/**
 * Extracts raw text from client File object (PDF, DOCX, DOC, TXT)
 */
export async function extractTextFromFile(file) {
  const name = file.name.toLowerCase();

  if (name.endsWith('.pdf')) {
    const arrayBuffer = await file.arrayBuffer();
    try {
      const text = await extractPdfText(arrayBuffer);
      if (text && text.trim().length > 10) {
        return text;
      }
    } catch (err) {
      console.warn('PDF.js line-grouping extraction fallback:', err);
    }
    
    // Basic fallback if line-grouping fails
    const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer });
    const pdf = await loadingTask.promise;
    let fullText = '';
    for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
      const page = await pdf.getPage(pageNum);
      const textContent = await page.getTextContent();
      const pageStrings = textContent.items.map(item => item.str);
      fullText += pageStrings.join(' ') + '\n';
    }
    return fullText;
  } else if (name.endsWith('.docx') || name.endsWith('.doc')) {
    const arrayBuffer = await file.arrayBuffer();
    try {
      const htmlResult = await mammoth.convertToHtml({ arrayBuffer });
      if (htmlResult && htmlResult.value && htmlResult.value.trim().length > 0) {
        const convertedText = convertMammothHtmlToText(htmlResult.value);
        if (convertedText && convertedText.trim().length > 20) {
          return convertedText;
        }
      }
    } catch (err) {
      console.warn('Mammoth HTML conversion fallback to raw text:', err.message);
    }
    const rawResult = await mammoth.extractRawText({ arrayBuffer });
    return rawResult.value;
  } else {
    // Plain text fallback
    return await file.text();
  }
}

/**
 * Preprocesses raw text: normalizes line endings and splits single-line options
 */
export function preprocessText(rawText) {
  if (!rawText || typeof rawText !== 'string') return '';

  let cleanText = rawText
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .replace(/\u00a0/g, ' ')
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    .replace(/[\u2013\u2014]/g, '-');

  const lines = cleanText.split('\n').map(l => l.trim()).filter(Boolean);
  const resultLines = [];

  // Pattern to catch horizontal inline options (e.g. "A) Apple  B) Banana  C) Cat  D) Dog" or "(a) 10 (b) 20 (c) 30 (d) 40")
  const inlineOptionPattern = /(?:^|\s+)(?:[\(\[]?([A-Da-d1-5])[\.\)\]]\s*|\b([A-Da-d])[\.\)]\s+)(?=\S)/g;

  for (const line of lines) {
    const matches = [...line.matchAll(inlineOptionPattern)];

    if (matches.length >= 2) {
      for (let i = 0; i < matches.length; i++) {
        const match = matches[i];
        const matchStart = match.index;

        if (i === 0 && matchStart > 0) {
          const prefix = line.substring(0, matchStart).trim();
          if (prefix) resultLines.push(prefix);
        }

        const nextStart = (i < matches.length - 1) ? matches[i + 1].index : line.length;
        const optionChunk = line.substring(matchStart, nextStart).trim();
        if (optionChunk) resultLines.push(optionChunk);
      }
    } else {
      resultLines.push(line);
    }
  }

  return resultLines.join('\n');
}

/**
 * Smart Regex Parser to convert plain text question paper into structured questions & options
 */
export function parseQuestionsFromText(rawText) {
  if (!rawText || typeof rawText !== 'string') return [];

  const processedText = preprocessText(rawText);
  const lines = processedText.split('\n').map(l => l.trim()).filter(Boolean);

  const rawQuestions = [];
  let currentQuestion = null;

  // Flexible Regex patterns supporting Q1, Q.1, Question 1, 1., 1), (1), [1], I., II., 1-, Q1)
  const questionHeaderRegex = /^(?:(?:Q(?:uestion|ue)?\.?\s*(?:no\.?|num\.?)?\s*(\d+))|(?:Q|\b)(\d{1,3})[\.\)\:\-\/]|\[(\d{1,3})\]|\((\d{1,3})\)|(?:[I|V|X]{1,4})[\.\)\:\-])\s*[:\-]?\s*(.*)/i;
  
  // Option Regex supporting A), A., (A), [A], a), a., (a), 1), (1), i), (i), *A), Option A:
  const optionRegex = /^(?:\*\s*)?(?:(?:Option\s+)?[\(\[]?([A-Da-d1-5]|[iI]{1,3}|iv|v)[\.\)\]\:\-]\s*|\b([A-Da-d])[\.\)\:]\s+)(.*)/i;
  
  // Answer line regex supporting Answer: A, Ans: B, Correct: C, Ans - (D), Ans: option 2
  const answerHeaderRegex = /^(?:Answer|Ans|Correct Answer|Correct|Answer Key)\s*[:\-]?\s*(?:Option\s*)?\(?([A-Da-d1-5]|.*)\)?/i;
  
  // Global Answer Key at bottom of paper
  const globalAnswerKeyHeaderRegex = /^(?:Answer Key|Answers|Correct Answers|Answer Sheet)\s*[:\-]?/i;

  let globalAnswersMap = {};
  let inAnswerKeySection = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (globalAnswerKeyHeaderRegex.test(line)) {
      inAnswerKeySection = true;
    }

    if (inAnswerKeySection) {
      const keyPairs = [...line.matchAll(/(?:Q\.?\s*)?(\d+)\s*[\.\:\-\=]\s*\(?([A-Da-d1-5])\)?/g)];
      if (keyPairs.length > 0) {
        for (const kp of keyPairs) {
          globalAnswersMap[kp[1]] = kp[2].toUpperCase();
        }
        continue;
      } else if (line.match(globalAnswerKeyHeaderRegex)) {
        continue;
      }
    }

    const ansMatch = line.match(answerHeaderRegex);
    if (ansMatch && currentQuestion) {
      currentQuestion.correct_answer = ansMatch[1].trim().toUpperCase();
      continue;
    }

    const qMatch = line.match(questionHeaderRegex);
    if (qMatch) {
      const qNum = qMatch[1] || qMatch[2] || qMatch[3] || qMatch[4] || '';
      const qText = qMatch[5] || line;

      if (currentQuestion && currentQuestion.options.length >= 2) {
        rawQuestions.push(currentQuestion);
      }
      currentQuestion = {
        num: qNum,
        question_text: qText.trim(),
        options: [],
        correct_answer: '',
        marks: 1
      };
      continue;
    }

    const optMatch = line.match(optionRegex);
    if (optMatch) {
      const optKey = (optMatch[1] || optMatch[2] || '').toUpperCase();
      let optText = (optMatch[3] || line).trim();
      const isAsteriskCorrect = line.startsWith('*');

      // Check if option text ends with (Correct) or [Ans] or (Answer)
      const inlineCorrectMatch = optText.match(/[\(\[]?(?:correct|ans|right answer)[\)\]]?$/i);
      let isInlineCorrect = false;
      if (inlineCorrectMatch) {
        isInlineCorrect = true;
        optText = optText.replace(/[\(\[]?(?:correct|ans|right answer)[\)\]]?$/i, '').trim();
      }

      if (currentQuestion && currentQuestion.options.some(o => o.key === optKey)) {
        if (currentQuestion.options.length >= 2) {
          rawQuestions.push(currentQuestion);
        }
        currentQuestion = {
          question_text: 'Question',
          options: [],
          correct_answer: '',
          marks: 1
        };
      }

      if (!currentQuestion) {
        currentQuestion = {
          question_text: 'Question',
          options: [],
          correct_answer: '',
          marks: 1
        };
      }

      const newOpt = {
        id: `opt_${currentQuestion.options.length + 1}`,
        text: optText,
        key: optKey
      };
      currentQuestion.options.push(newOpt);

      if (isAsteriskCorrect || isInlineCorrect) {
        currentQuestion.correct_answer = optKey;
      }
      continue;
    }

    if (currentQuestion) {
      if (currentQuestion.options.length === 0) {
        currentQuestion.question_text += '\n' + line;
      } else {
        if (currentQuestion.options.length >= 4 && isLikelyQuestionSentence(line)) {
          rawQuestions.push(currentQuestion);
          currentQuestion = {
            question_text: line,
            options: [],
            correct_answer: '',
            marks: 1
          };
        } else {
          const lastOpt = currentQuestion.options[currentQuestion.options.length - 1];
          lastOpt.text += '\n' + line;
        }
      }
    } else {
      if (line.length > 5 && !line.toLowerCase().startsWith('quiz') && !line.toLowerCase().startsWith('test')) {
        currentQuestion = {
          question_text: line,
          options: [],
          correct_answer: '',
          marks: 1
        };
      }
    }
  }

  if (currentQuestion && currentQuestion.options.length >= 2) {
    rawQuestions.push(currentQuestion);
  }

  if (Object.keys(globalAnswersMap).length > 0) {
    rawQuestions.forEach((q, index) => {
      const qIndexStr = String(index + 1);
      const qNumStr = q.num || qIndexStr;
      const targetAns = globalAnswersMap[qNumStr] || globalAnswersMap[qIndexStr];

      if (targetAns && !q.correct_answer) {
        q.correct_answer = targetAns;
      }
    });
  }

  const questions = rawQuestions.map(q => finalizeQuestion(q));

  // Secondary Fallback: If no structured questions were found via regex, chunk text intelligently
  if (questions.length === 0 && lines.length >= 5) {
    let tempQ = null;
    lines.forEach((l, idx) => {
      if (idx % 5 === 0) {
        if (tempQ) questions.push(finalizeQuestion(tempQ));
        tempQ = { question_text: l, options: [], correct_answer: '', marks: 1 };
      } else if (tempQ && tempQ.options.length < 4) {
        tempQ.options.push({
          id: `opt_${tempQ.options.length + 1}`,
          text: l,
          key: String.fromCharCode(65 + tempQ.options.length)
        });
      }
    });
    if (tempQ && tempQ.options.length >= 2) {
      questions.push(finalizeQuestion(tempQ));
    }
  }

  return questions;
}

function isLikelyQuestionSentence(line) {
  if (!line || line.length < 5) return false;
  if (line.endsWith('?')) return true;

  const lower = line.toLowerCase();
  const questionWords = ['what', 'which', 'how', 'why', 'who', 'where', 'when', 'explain', 'calculate', 'find', 'select', 'consider', 'identify', 'choose'];
  return questionWords.some(w => lower.startsWith(w));
}

function finalizeQuestion(q) {
  let correctId = q.options[0]?.id || 'opt_1';

  if (q.correct_answer) {
    const targetKey = q.correct_answer.toUpperCase().trim();
    const matchedOpt = q.options.find(
      opt => opt.key === targetKey || opt.text.toLowerCase() === targetKey.toLowerCase() || opt.text.toLowerCase().includes(targetKey.toLowerCase())
    );
    if (matchedOpt) {
      correctId = matchedOpt.id;
    } else {
      // Numerical match: e.g. answer is "1" or "2" for option A/B
      const numMatch = targetKey.match(/^(\d+)$/);
      if (numMatch) {
        const numIdx = parseInt(numMatch[1], 10) - 1;
        if (q.options[numIdx]) {
          correctId = q.options[numIdx].id;
        }
      }
    }
  }

  const cleanOptions = q.options.map((opt, i) => ({
    id: `opt_${i + 1}`,
    text: opt.text
  }));

  return {
    question_text: q.question_text,
    question_type: 'mcq',
    options: cleanOptions,
    correct_answer: correctId,
    marks: Number(q.marks) || 1,
    explanation: ''
  };
}

/**
 * Process client-uploaded File and return structured tagged questions
 */
export async function parseDocumentFile(file) {
  if (!file) throw new Error('No document file selected.');

  const importSessionId = `doc_imp_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
  const rawText = await extractTextFromFile(file);
  const extractedQuestions = parseQuestionsFromText(rawText);

  if (extractedQuestions.length === 0) {
    throw new Error('Could not extract multiple-choice questions automatically from this file. Please verify file format or create questions manually.');
  }

  const taggedQuestions = extractedQuestions.map((q, idx) => ({
    ...q,
    source_metadata: {
      import_session_id: importSessionId,
      doc_name: file.name,
      parsed_at: new Date().toISOString(),
      question_index: idx + 1
    }
  }));

  return {
    success: true,
    importSessionId,
    filename: file.name,
    extractedCount: taggedQuestions.length,
    questions: taggedQuestions
  };
}

